//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input Assets/EventInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @EventInputAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @EventInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""EventInputAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""3af944af-8f03-4256-a1dc-64dfdc96fd15"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""2ba41473-a7d5-4197-9c06-b4c6651b9ff7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Use"",
                    ""type"": ""Button"",
                    ""id"": ""2861b5ec-8ed6-4000-9306-27d78ba1e2be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""selfHarmHealth"",
                    ""type"": ""Button"",
                    ""id"": ""c1affc5e-9384-4f1c-b75e-bc9a0b066850"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""selftHealHealth"",
                    ""type"": ""Button"",
                    ""id"": ""8c78d669-ecdd-448f-950c-4b3a2e6a2047"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""selftHarmSanity"",
                    ""type"": ""Button"",
                    ""id"": ""319b6c43-0f48-41c4-bcfb-eec96b9a2159"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""selftHealSanity"",
                    ""type"": ""Button"",
                    ""id"": ""8ee655d3-d2db-44c4-a327-a0176c149dc1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DoT"",
                    ""type"": ""Button"",
                    ""id"": ""d6500cfb-0652-4bd2-a538-efd1961e1e26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""871dcc97-abad-43cd-99cc-d696b23ae7da"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3d8fe835-80a8-4a91-92e0-8358ac4a9e88"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8d8e6bb8-a5f8-4a63-8923-f82e2cb5fcb7"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2db33f8a-35a6-44d9-ab00-183677843412"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b1fd6a38-5a30-4be6-8294-3d502474caae"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""07bb7cf1-0749-49e5-b7b3-a3250ad10054"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""81166ca2-7df6-4e39-b500-339aca4bcf6a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""12376780-8c90-414b-a39f-7f66263158cb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b8fddf04-98e9-4123-9593-0058c9341076"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4d80c493-48a2-42da-a0d2-47bc6b4941bd"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a021904-b394-4fdd-a994-77e433c9c8be"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""selfHarmHealth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5de5d089-3f38-4355-931a-24a698686dfb"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""selftHealHealth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c88a3f9-f1b1-423f-b243-54d5757e9e50"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""selftHarmSanity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f30b91b9-fac2-4609-a7d1-c6e08b6ebf54"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""selftHealSanity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72ee6934-cc97-4cb9-baca-ae8e17c9b0e9"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Use = m_Player.FindAction("Use", throwIfNotFound: true);
        m_Player_selfHarmHealth = m_Player.FindAction("selfHarmHealth", throwIfNotFound: true);
        m_Player_selftHealHealth = m_Player.FindAction("selftHealHealth", throwIfNotFound: true);
        m_Player_selftHarmSanity = m_Player.FindAction("selftHarmSanity", throwIfNotFound: true);
        m_Player_selftHealSanity = m_Player.FindAction("selftHealSanity", throwIfNotFound: true);
        m_Player_DoT = m_Player.FindAction("DoT", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Use;
    private readonly InputAction m_Player_selfHarmHealth;
    private readonly InputAction m_Player_selftHealHealth;
    private readonly InputAction m_Player_selftHarmSanity;
    private readonly InputAction m_Player_selftHealSanity;
    private readonly InputAction m_Player_DoT;
    public struct PlayerActions
    {
        private @EventInputAction m_Wrapper;
        public PlayerActions(@EventInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Use => m_Wrapper.m_Player_Use;
        public InputAction @selfHarmHealth => m_Wrapper.m_Player_selfHarmHealth;
        public InputAction @selftHealHealth => m_Wrapper.m_Player_selftHealHealth;
        public InputAction @selftHarmSanity => m_Wrapper.m_Player_selftHarmSanity;
        public InputAction @selftHealSanity => m_Wrapper.m_Player_selftHealSanity;
        public InputAction @DoT => m_Wrapper.m_Player_DoT;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Use.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUse;
                @Use.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUse;
                @Use.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUse;
                @selfHarmHealth.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelfHarmHealth;
                @selfHarmHealth.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelfHarmHealth;
                @selfHarmHealth.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelfHarmHealth;
                @selftHealHealth.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelftHealHealth;
                @selftHealHealth.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelftHealHealth;
                @selftHealHealth.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelftHealHealth;
                @selftHarmSanity.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelftHarmSanity;
                @selftHarmSanity.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelftHarmSanity;
                @selftHarmSanity.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelftHarmSanity;
                @selftHealSanity.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelftHealSanity;
                @selftHealSanity.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelftHealSanity;
                @selftHealSanity.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelftHealSanity;
                @DoT.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDoT;
                @DoT.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDoT;
                @DoT.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDoT;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Use.started += instance.OnUse;
                @Use.performed += instance.OnUse;
                @Use.canceled += instance.OnUse;
                @selfHarmHealth.started += instance.OnSelfHarmHealth;
                @selfHarmHealth.performed += instance.OnSelfHarmHealth;
                @selfHarmHealth.canceled += instance.OnSelfHarmHealth;
                @selftHealHealth.started += instance.OnSelftHealHealth;
                @selftHealHealth.performed += instance.OnSelftHealHealth;
                @selftHealHealth.canceled += instance.OnSelftHealHealth;
                @selftHarmSanity.started += instance.OnSelftHarmSanity;
                @selftHarmSanity.performed += instance.OnSelftHarmSanity;
                @selftHarmSanity.canceled += instance.OnSelftHarmSanity;
                @selftHealSanity.started += instance.OnSelftHealSanity;
                @selftHealSanity.performed += instance.OnSelftHealSanity;
                @selftHealSanity.canceled += instance.OnSelftHealSanity;
                @DoT.started += instance.OnDoT;
                @DoT.performed += instance.OnDoT;
                @DoT.canceled += instance.OnDoT;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnUse(InputAction.CallbackContext context);
        void OnSelfHarmHealth(InputAction.CallbackContext context);
        void OnSelftHealHealth(InputAction.CallbackContext context);
        void OnSelftHarmSanity(InputAction.CallbackContext context);
        void OnSelftHealSanity(InputAction.CallbackContext context);
        void OnDoT(InputAction.CallbackContext context);
    }
}
